CREATE TABLE images (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL
);

INSERT INTO images (url) VALUES
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/alexander-grey-jYbKxinWQGk-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/artur-luczka-loAfOVk1eNc-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/blue-gradient-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/daniel-leone-g30P1zcOzXo-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/darkblue-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/dave-hoefler-lsoogGC_5dg-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/david-marcu-78A265wPiO4-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/davies-designs-studio-_UCVrH-ZIIg-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/eberhard-grossgasteiger-S-2Ukb_VqpA-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/eberhard-grossgasteiger-y2azHvupCVo-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/goutham-krishna-h5wvMCdOV3w-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/green-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/guillaume-briard-lSXpV8bDeMA-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/j-lee-5WFfI63aEBo-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/janke-laskowski-jz-ayLjk2nk-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/jonatan-pie-EvKBHBGgaUo-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/lightblue-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/lightpurple-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/mads-schmidt-rasmussen-xfngap_DToE-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/matthew-mcbrayer-qD9xzm7yK9U-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/micah-boswell-OPnBJ5L2oxs-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/nareeta-martin-pEWtWnDgGLs-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/orange-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/pink-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/purple-pink-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/purple-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/qingbao-meng-01_igFr7hd4-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/red-orange-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/red-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/resul-mentes-DbwYNr8RPbg-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/rohit-ranwa-twEy5TouJLg-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/sam-dan-truong-ju2NgSoR6pA-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/shifaaz-shamoon-9K9ipjhDdks-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/steffi-Cj0tPzC5Uic-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/teemu-paananen-OOE4xAnBhKo-unsplash.jpg'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/white-square.png'),
	('https://github.com/jwelkener/InstaBible2/blob/main/static/images/yellow-square.png');
